### ISSUE TITLE
ofxDSHapVideoPlayer overwrites draw color

### ISSUE THREAD

**Issue by Echolaitoc** [secondstory/ofxDSHapVideoPlayer#11]
The `ofxDSHapVideoPlayer::draw(int x, int y, int w, int h)` method has a hardcoded `ofSetColor(255);`.
This makes it impossible to fade videos in and out, since the alpha is always set to full opacity. It also affects drawing after the ofxDSHapVideoPlayer, as there are no `ofPushStyle()` / `ofPopStyle()`.
I'd suggest removing the ofSetColor and leaving it up to the user to set the draw color.

**Comment by sheridanis** [comment]
+1

**Comment by mantissa** [comment]
thanks for pointing that out (and for the +1), what bad practice :)
it's fixed now
