### ISSUE TITLE
Cinder port - Glew required?

### ISSUE THREAD

**Issue by LightAct** [secondstory/ofxDSHapVideoPlayer#12]
Hi,

First, thanks for sharing your addon.

I am trying to create a cinder port, but am bumping into a few issues. For example, in ofxDSHapVideoPlayer.cpp line 1412 (glGetTexLevelParameteriv) and line 1414 (glCompressedTexSubImage2D) keep throwing GL_INVALID_OPERATION  error. I checked the value of all the parameters in these functions and they are exactly the same in your addon and my cinder port. 

The only difference is that I don't include glew and you do and glew.h includes some redefitions of these functions. Do you have any knowledge if this might be the reason for the invalid operation error I am getting?

Thanks!

**Comment by LightAct** [comment]
Also, why do you use Glew anyway? Are you using any OpenGL extensions?

Thanks!

**Comment by mantissa** [comment]
Hi. I'm glad that you're porting this to Cinder. I can't remember why I used Glew off the top of my head but will look at the code again (it's been a few years!).

**Comment by mantissa** [comment]
looks like that's part of the OF project source code

**Comment by LightAct** [comment]
Hi,

Yes, I figured that out. Thanks anyway. I managed to make the port working and you can get it [here](https://github.com/lightact/HAP-Cinder).

Thanks for creating this addon!

**Comment by mantissa** [comment]
Super!! Sure thing.
