### ISSUE TITLE
Convert to AVI with DXT

### ISSUE THREAD

**Issue by gomesgustavo** [secondstory/ofxDSHapVideoPlayer#15]
Hi,

We are using Adobe Media Encodeer to convert the avi file on windows.
The option "use snappy compression" is checked by default and is not possible to uncheck it because the option is disabled.

Do you know how can I convert the .avi with DXT option?
We don't need to access the texture data...

We tried to generate with ffmpeg and quicktime with no luck.

**Comment by mantissa** [comment]
Hi, this is a bug with AME. I do believe that you can fix it by deleting preference files. Maybe ping the Renderheads folks?! Anyway, snappy is additional compression for DXT and will generate readable files for ofxDSHapVideoPlayer. Hope that helps!
