### ISSUE TITLE
Unresolved external symbol load 64-bit

### ISSUE THREAD

**Issue by Ernesto505** [secondstory/ofxDSHapVideoPlayer#2]
Hi,

I am trying to compile my application (I am getting the same error with the example code) and I am getting an unresolved external symbol error. 

Severity    Code    Description Project File    Line    Suppression State
Error   LNK2019 unresolved external symbol gluErrorString referenced in function "public: virtual bool __cdecl ofxDSHapVideoPlayer::load(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?load@ofxDSHapVideoPlayer@@UEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)  ofxDSHapVideoPlayerExample I:\of_v0.9.0_vs_release\addons\ofxDSHapVideoPlayer\example\ofxDSHapVideoPlayer.obj   1

I am on OF 0.9.0 and I am using Visual Studio 2015 Community Version. I am trying to compile in 64-bits (it works fine for 32-bits).

**Comment by mantissa** [comment]
Hey Ernesto, I'm sorry for the late response. Did you ever resolve this compiler issue? Curious if you ran into the same problem with the sample code (which does compile as a 64-bit application)

**Comment by tobiasebsen** [comment]
The linker error is caused by the call to gluErrorString in the GLU library, which only exist in a 32-bit version. I would suggest commenting out the lines in the code – or even better: write a custom getGlErrorString() to implement.

**Comment by Ernesto505** [comment]
Thanks for the replies and sorry for the late response!

I moved on a different project now but I will come back to it and update you with the results.

**Comment by Ernesto505** [comment]
So thanks for the suggestion @tobiasebsen! 

This worked for the sample app. Now I have to sort it out for my application. Hopefully this would be straightforward.
