### ISSUE TITLE
Failed to create OpenGL texture

### ISSUE THREAD

**Issue by TROTech** [secondstory/ofxDSHapVideoPlayer#4]
I'm trying to build your example in VisualStudio 2015.  I've placed a HAP encoded MOV file in bin/data/ and updated hapPlayer.load() to reference it.

It compiles, but once running it throws these errors in the console.

> warning: pin not connected
> [ error ] ofxDSHapVideoPlayer: Failed to create OpenGL texture: width and/or height are zero
> [ error ] ofTexture: getTextureData(): texture has not been allocated
> error invalid operation

OpenFrameworks 0.9.3
VisualStudio 2015
Windows 10 64bit
Intel HD Graphics 5500 (ultrabook)

**Comment by mantissa** [comment]
Hey TROTech, is this error with a file that you encoded? If so, how did you encode it? Also – did the player work with Renderheads demo files (http://downloads.renderheads.com/2014/sample-1080p30-Hap.avi)? Please note that this DirectShow HAP player works with .avi files.

**Comment by TROTech** [comment]
Perfect, that did the trick!  I'm happy to use AVI.

The MOV file I was trying, was a sample file from http://vdmx.vidvox.net/.
